(source gnu)
(source melpa)
(source marmalade)

(depends-on "anything")
(depends-on "auto-complete")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "magit")
(depends-on "egg" :git "git@github.com:byplayer/egg.git")
(depends-on "popwin" :git "git@github.com:m2ym/popwin-el.git")

;; Web
(depends-on "markdown-mode" : "git@github.com:defunkt/markdown-mode.git")
(depends-on "web-mode")
(depends-on "emmet-mode")

;; programming modes

;; JavaScript
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "tern")
(depends-on "tern-auto-complete")
