(source gnu)
(source melpa)
(source marmalade)

(depends-on "anything")
(depends-on "auto-complete")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "egg" :git "git@github.com:byplayer/egg.git")

(depends-on "markdown-mode" : "git@github.com:defunkt/markdown-mode.git")
(depends-on "web-mode")

;; programming modes
(depends-on "js2-mode")

(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "ruby-end")
